language: julia
julia:
  - 0.6.2
after_success:
  - julia -e 'cd(Pkg.dir("GpAbc")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder()); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'

