branches:
  only:
  - master
  - /^v[\d.]+$/
language: julia
julia:
  - 1.0
after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia --project=docs/ docs/make.jl
